title: CasinoGuidesNP
description: Expert casino gaming guides in Nepali for Nepalese players.
baseurl: "/casinoguidesnp"
url: "https://bb8bdt-ops.github.io"
lang: ne
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
